# Generated by Django 5.1.7 on 2025-03-16 21:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validarcodigo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosecreto',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
