# Generated by Django 5.1.7 on 2025-03-16 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validarcodigo_app', '0002_alter_codigosecreto_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosecreto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
