# Generated by Django 5.1.7 on 2025-03-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validarcodigo_app', '0003_alter_codigosecreto_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosecreto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
