# Generated by Django 5.1.7 on 2025-03-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validarcodigo_app', '0004_alter_codigosecreto_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigosecreto',
            options={'verbose_name': 'Gerar Codigo Secreto', 'verbose_name_plural': 'Gerar Codigo Secretos'},
        ),
    ]
