# Generated by Django 4.2.20 on 2025-04-09 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosObrigatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='telefone_chaveiro')),
                ('whatsapp', models.CharField(blank=True, max_length=15, verbose_name='whatsapp_chaveiro')),
                ('data_nascimento', models.DateField()),
                ('idade', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_obrigatorios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DadosOpcionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=30)),
                ('numero_endereco', models.CharField(blank=True, max_length=10, verbose_name='numero')),
                ('complemento', models.CharField(blank=True, max_length=30)),
                ('cidade', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre (AC)'), ('AL', 'Alagoas (AL)'), ('AP', 'Amapá (AP)'), ('AM', 'Amazonas (AM)'), ('BA', 'Bahia (BA)'), ('CE', 'Ceará (CE)'), ('DF', 'Distrito Federal (DF)'), ('ES', 'Espírito Santo (ES)'), ('GO', 'Goiás (GO)'), ('MA', 'Maranhão (MA)'), ('MT', 'Mato Grosso (MT)'), ('MS', 'Mato Grosso do Sul (MS)'), ('MG', 'Minas Gerais (MG)'), ('PA', 'Pará (PA)'), ('PB', 'Paraíba (PB)'), ('PR', 'Paraná (PR)'), ('PE', 'Pernambuco (PE)'), ('PI', 'Piauí (PI)'), ('RJ', 'Rio de Janeiro (RJ)'), ('RN', 'Rio Grande do Norte (RN)'), ('RS', 'Rio Grande do Sul (RS)'), ('RO', 'Rondônia (RO)'), ('RR', 'Roraima (RR)'), ('SC', 'Santa Catarina (SC)'), ('SP', 'São Paulo (SP)'), ('SE', 'Sergipe (SE)'), ('TO', 'Tocantins (TO)')], max_length=2, verbose_name='uf')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='sangue')),
                ('alergias_intolerancias', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('link_whatsapp', models.URLField(blank=True, verbose_name='link-whats')),
                ('links_outros', models.URLField(blank=True, verbose_name='link-outros')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dados_obrigatorios', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_opcionais', to='chaveiros.dadosobrigatorios')),
            ],
        ),
    ]
