# Generated by Django 4.2.20 on 2025-04-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaveiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosopcionais',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dadosopcionais',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
