# Generated by Django 4.2.20 on 2025-04-09 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosOpcionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=3)),
                ('alergias_intolerancias', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('link_whatsapp', models.URLField(blank=True)),
                ('links_outros', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='complemento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(blank=True, max_length=30, verbose_name='uf'),
        ),
        migrations.AddField(
            model_name='user',
            name='numero_endereco',
            field=models.CharField(blank=True, max_length=10, verbose_name='numero'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto_profile',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfils/'),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='dadosopcionais',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_opcionais', to=settings.AUTH_USER_MODEL),
        ),
    ]
