# Generated by Django 4.2.20 on 2025-04-09 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_dadosopcionais_remove_user_bio_user_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='idade',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre (AC)'), ('AL', 'Alagoas (AL)'), ('AP', 'Amapá (AP)'), ('AM', 'Amazonas (AM)'), ('BA', 'Bahia (BA)'), ('CE', 'Ceará (CE)'), ('DF', 'Distrito Federal (DF)'), ('ES', 'Espírito Santo (ES)'), ('GO', 'Goiás (GO)'), ('MA', 'Maranhão (MA)'), ('MT', 'Mato Grosso (MT)'), ('MS', 'Mato Grosso do Sul (MS)'), ('MG', 'Minas Gerais (MG)'), ('PA', 'Pará (PA)'), ('PB', 'Paraíba (PB)'), ('PR', 'Paraná (PR)'), ('PE', 'Pernambuco (PE)'), ('PI', 'Piauí (PI)'), ('RJ', 'Rio de Janeiro (RJ)'), ('RN', 'Rio Grande do Norte (RN)'), ('RS', 'Rio Grande do Sul (RS)'), ('RO', 'Rondônia (RO)'), ('RR', 'Roraima (RR)'), ('SC', 'Santa Catarina (SC)'), ('SP', 'São Paulo (SP)'), ('SE', 'Sergipe (SE)'), ('TO', 'Tocantins (TO)')], max_length=2, verbose_name='uf'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto_profile',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfis/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='telefone_chaveiro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, verbose_name='whatsapp_chaveiro'),
        ),
        migrations.DeleteModel(
            name='DadosOpcionais',
        ),
    ]
